apiVersion: "sample.javaoperatorsdk/v1"
kind: WebPage
metadata:
  name: hello
spec:
  html: |
    <html>
      <head>
        <title>WebPage Operator</title>
      </head>
      <body>
        Hello World!
      </body>
    </html>
